# Generated by Django 4.1.7 on 2023-03-13 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=8)),
                ('matricula', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'Aluno',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id_atividade', models.AutoField(primary_key=True, serialize=False)),
                ('atividade', models.TextField()),
                ('tipo', models.CharField(choices=[('sala', 'Atividade de sala'), ('casa', 'Atividade de casa'), ('prova', 'Prova')], max_length=50)),
                ('data_postagem', models.DateField()),
                ('data_entrega', models.DateField()),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'db_table': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=7)),
                ('carga_horaria', models.IntegerField()),
                ('ementa', models.TextField()),
            ],
            options={
                'verbose_name': 'Diciplina',
                'verbose_name_plural': 'Diciplinas',
                'db_table': 'Diciplina',
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id_frequencia', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=8)),
                ('codigo', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'db_table': 'Professor',
            },
        ),
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id_plano_aula', models.AutoField(primary_key=True, serialize=False)),
                ('tema_aula', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('metodo', models.CharField(choices=[('Teorica', 'Teorica'), ('Pratica', 'Pratica')], max_length=50)),
                ('dia', models.DateField()),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.disciplina')),
            ],
            options={
                'verbose_name': 'Plano de aula',
                'verbose_name_plural': 'Planos de aula',
                'db_table': 'PlanoAula',
            },
        ),
        migrations.CreateModel(
            name='FrequenciaAluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('presenca', models.CharField(default='T', max_length=1)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.aluno')),
                ('id_frequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.frequencia')),
            ],
            options={
                'verbose_name': 'Frequencia de aluno',
                'verbose_name_plural': 'Frequências de alunos',
                'db_table': 'FrequenciaAluno',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaAluno',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField(default=0.0)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.aluno')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina Aluno',
                'verbose_name_plural': 'Disciplinas dos Alunos',
                'db_table': 'DisciplinaAluno',
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.professor'),
        ),
        migrations.CreateModel(
            name='AtividadeAluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField()),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.aluno')),
                ('id_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.atividade')),
            ],
            options={
                'verbose_name': 'Atividade do Aluno',
                'verbose_name_plural': 'Atividades dos Alunos',
                'db_table': 'AtividadeAluno',
            },
        ),
        migrations.AddField(
            model_name='atividade',
            name='id_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.disciplina'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='id_plano_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.planoaula'),
        ),
    ]
